// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/dot.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/Toggle.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/dot.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/Toggle.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
