// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $dot from "./routes/dot.ts";
import * as $index from "./routes/index.tsx";
import * as $Toggle from "./islands/Toggle.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/dot.ts": $dot,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Toggle.tsx": $Toggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
